name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: postboys/workflows/.github/workflows/build-nodejs.yml@main
    with:
      path-to-artifact: src/**/*.js

  publish:
    needs: build
    uses: postboys/workflows/.github/workflows/npm-publish.yml@main
    permissions:
      id-token: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
