name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  build:
    uses: camarojs/workflows/.github/workflows/build-nodejs.yml@main
    with:
      path-to-artifact: |
        lib/**/*
        .npmignore

  publish:
    needs: build
    uses: camarojs/workflows/.github/workflows/npm-publish.yml@main
    permissions:
      id-token: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
